packages:
  - 'packages/*'

injectWorkspacePackages: true

# See: https://pnpm.io/supply-chain-security
blockExoticSubdeps: true
minimumReleaseAge: 20160 # 14 days (keep in sync with Renovate config)
minimumReleaseAgeExclude:
  - '@api3/*'
  # Renovate security update: axios@1.15.0 || 1.15.2
  - axios@1.15.0 || 1.15.2
  # Renovate security update: lodash@4.18.1
  - lodash@4.18.1
