version: '3.8'
services:
  dynamodb-local:
    command: '-jar DynamoDBLocal.jar -sharedDb'
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-local
    working_dir: /home/dynamodblocal
    ports:
      - 8000:8000
