service: nodary-signature-pool
useDotenv: true
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

  stage: dev
  region: us-east-2

  httpApi:
    disableDefaultEndpoint: true
    id: ${env:HTTP_API_ID}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
            - "dynamodb:Query"
            - "dynamodb:BatchWriteItem"

          Resource:
            - { "Fn::GetAtt": ["SignedDataPool", "Arn"] }

  environment:
    MAX_BATCH_SIZE: ${env:MAX_BATCH_SIZE}

# package:
#   patterns:
#     - "!.build/**"
#     - "!.vscode/**"
#     - "!node_modules/**"
#     - "!test/**"

functions:
  upsertData:
    memorySize: 192
    handler: src/handlers.upsertData
    events:
      - httpApi:
          path: /
          method: put
  batchUpsertData:
    memorySize: 512
    handler: src/handlers.batchUpsertData
    events:
      - httpApi:
          path: /
          method: post
  getData:
    memorySize: 192
    handler: src/handlers.getData
    events:
      - httpApi:
          path: /{airnode}
          method: get
  listAirnodeAddresses:
    memorySize: 192
    handler: src/handlers.listAirnodeAddresses
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript

resources:
  Resources:
    SignedDataPool:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: signedDataPool
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: airnode
            AttributeType: S
          - AttributeName: templateId
            AttributeType: S
        KeySchema:
          - AttributeName: airnode
            KeyType: HASH
          - AttributeName: templateId
            KeyType: RANGE
